apiVersion: v1
kind: Service
metadata:
  name: quarkus-api
spec:
  selector:
    app: quarkus-api
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.port }}
  type: {{ .Values.service.type }}
